# Language
language: node_js
node_js: 
  - '10'
  - '8'

scripts:
  - npm run test
  - npm run build

branches:
  only:
    - master
#Superuser premission
sudo: required
# Docker CLI needs to be preinstalled
services:
  - docker

# Build image before install
before_install:
  - docker build -t tl9474/docker-workflow -f Dockerfile.dev .
 
script:
  - docker run tl9474/docker-workflow npm run test -- -- coverage
